// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NVN123.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211215080816_Create_Table_NVN123")]
    partial class Create_Table_NVN123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NVN123.Models.NVN", b =>
                {
                    b.Property<string>("NVNID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NVNName")
                        .HasColumnType("TEXT");

                    b.HasKey("NVNID");

                    b.ToTable("NVN");
                });

            modelBuilder.Entity("NVN123.Models.Person", b =>
                {
                    b.Property<string>("PersonID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("PersonNVN123");
                });
#pragma warning restore 612, 618
        }
    }
}
